# Generated by Django 3.1.7 on 2021-03-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='media/pexels-photo-2379004.jpeg', upload_to='media/'),
        ),
    ]
