# Generated by Django 3.1.7 on 2021-03-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210319_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
