# Generated by Django 3.1.7 on 2021-04-05 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_country_currency_deliverylocation_emailtemplate_language_orderstatus_stockstatus_tax_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='Country_id',
            new_name='country_id',
        ),
    ]
