# Generated by Django 3.1.7 on 2021-04-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_auto_20210405_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('homepage_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('image_right', models.ImageField(blank=True, null=True, upload_to='homepage_image_right/')),
                ('image_left', models.ImageField(blank=True, null=True, upload_to='homepage_image_left/')),
                ('subscribe_title', models.CharField(blank=True, max_length=100, null=True)),
                ('subscribe_content', models.TextField(blank=True, null=True)),
                ('subscribe_image', models.ImageField(blank=True, null=True, upload_to='homepage_subscribe_image')),
            ],
        ),
    ]
