# Generated by Django 3.1.7 on 2021-04-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
