# Generated by Django 3.1.7 on 2021-04-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_auto_20210407_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
