# Generated by Django 3.1.7 on 2021-04-07 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_auto_20210407_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
