# Generated by Django 3.1.7 on 2021-04-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_auto_20210407_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
