# Generated by Django 3.1.7 on 2021-04-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0012_varient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varient',
            name='sort_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
