# Generated by Django 3.1.7 on 2021-04-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0013_auto_20210408_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='varient',
            name='select_type',
            field=models.CharField(blank=True, choices=[('radio', 'Radio'), ('select', 'Select')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='varient',
            name='sort_order_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='varient',
            name='varient_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='varient',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
