# Generated by Django 3.1.7 on 2021-04-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0014_auto_20210409_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('seo_id', models.AutoField(primary_key=True, serialize=False)),
                ('meta_title', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_discriptor', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('social_id', models.AutoField(primary_key=True, serialize=False)),
                ('instagram', models.URLField(blank=True, max_length=100, null=True)),
                ('twitter', models.URLField(blank=True, max_length=100, null=True)),
                ('facebook', models.URLField(blank=True, max_length=100, null=True)),
                ('youtube', models.URLField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
