# Generated by Django 3.1.7 on 2021-03-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page_group_id',
            new_name='page_group_id_id',
        ),
    ]
