# Generated by Django 3.1.7 on 2021-03-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0002_auto_20210324_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevent',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
