# Generated by Django 3.1.7 on 2021-03-30 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210330_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
