# Generated by Django 3.1.7 on 2021-03-31 08:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210330_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('sku', models.CharField(blank=True, max_length=500, null=True)),
                ('product_slug', models.CharField(blank=True, max_length=200, null=True)),
                ('page_content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('upc', models.CharField(blank=True, max_length=100, null=True)),
                ('quentity', models.IntegerField(blank=True, null=True)),
                ('out_of_stock', models.CharField(blank=True, choices=[('instock', 'In Stock'), ('outstock', 'Out Stock')], max_length=100, null=True)),
                ('date_available', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('postal_code_verification', models.BooleanField(blank=True, null=True)),
                ('multiimage', models.ImageField(blank=True, null=True, upload_to='multiproduct/')),
                ('related_product', models.CharField(blank=True, max_length=100, null=True)),
                ('product_cost', models.IntegerField(blank=True, null=True)),
                ('add_product_cost', models.IntegerField(blank=True, null=True)),
                ('meta_tag_title', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_tag_discripation', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_tag_keyword', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('brand_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.brand')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_code', models.CharField(max_length=100)),
                ('coupon_description', models.TextField(blank=True, null=True)),
                ('coupon_type', models.CharField(blank=True, choices=[('pd', 'Percentage Discount'), ('ad', 'Amount Discount')], max_length=10, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('minimum_purchase_amount', models.IntegerField(blank=True, null=True)),
                ('maximum_purchase_amount', models.IntegerField(blank=True, null=True)),
                ('coupon_limit_use', models.IntegerField(blank=True, null=True)),
                ('no_of_times_use_discount', models.IntegerField(blank=True, null=True)),
                ('coupne_code_apply_all_item_in_the_cart', models.BooleanField(blank=True, null=True)),
                ('no_of_item_cart_apply_coupon', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
    ]
