# Generated by Django 3.1.7 on 2021-03-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_coupon_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
