# Generated by Django 3.1.7 on 2021-04-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210401_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
