# Generated by Django 3.1.7 on 2021-04-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_coupon_coupon_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(blank=True, choices=[('percentagediscount', 'Percentage Discount'), ('amountdiscount', 'Amount Discount')], max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='product_id',
        ),
        migrations.AddField(
            model_name='coupon',
            name='product_id',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.Product'),
        ),
    ]
