# Generated by Django 3.1.7 on 2021-04-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210402_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='day_left',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
