# Generated by Django 3.1.7 on 2021-04-19 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210408_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVarientInfo',
            fields=[
                ('varientinfo_id', models.AutoField(primary_key=True, serialize=False)),
                ('varientinfo_image', models.ImageField(blank=True, null=True, upload_to='vrientinfo_image/')),
                ('varientinfo_sku', models.CharField(blank=True, max_length=100, null=True)),
                ('varientinfo_price', models.IntegerField(blank=True, null=True)),
                ('varientinfo_barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('varientinfo_inventory', models.IntegerField(blank=True, null=True)),
                ('varientinfo_status', models.BooleanField(blank=True, null=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMultiImage',
            fields=[
                ('productimage_id', models.AutoField(primary_key=True, serialize=False)),
                ('multiimage', models.ImageField(blank=True, null=True, upload_to='product_multiimage/')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
    ]
