# Generated by Django 3.1.7 on 2021-04-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20210419_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='multiimage',
        ),
    ]
