# Generated by Django 3.1.7 on 2021-04-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_product_multiimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_type',
            field=models.CharField(blank=True, choices=[('value', 'Value'), ('percentage', 'Percentage')], max_length=100, null=True),
        ),
    ]
