# Generated by Django 3.1.7 on 2021-05-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20210420_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarientinfo',
            name='varientinfo_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
